### PR TITLE
Added hadoop-snappy format support

### PR DESCRIPTION
**Pull request by EliseAzure**
Sorry for lack of good quality tests, dont have much time these days :(
Tested hadoop-snappy compression a little bit with decompressing in HDFS cluster tho.

### CODE REVIEW

**Comment by EliseAzure** [comment]
Sorry for lack of good quality tests, dont have much time these days :(
Tested hadoop-snappy compression a little bit with decompressing in HDFS cluster tho.

**Comment by miyucy** [comment]
@EliseAzure Thanks for PR. I'm not familiar to hadoop snappy format.

Is hadoop snappy format is the same format as described in this [issue](https://github.com/kubo/snzip/issues/12#issue-127088400)?

**Comment by EliseAzure** [comment]
Yes, I actually just ported snzip logic for hadoop-snappy compression. Format is described here https://github.com/kubo/snzip#hadoop-snappy-format.
You can test it by compressing smth with the gem and decompressing with snzip or vice versa :)

**Comment by miyucy** [comment]
Thank you! I got it!

**Comment by miyucy** [comment]
I'll fix CI settings and release gem later. purhap next mornimg.

**Pull request merged**
