### PR TITLE
Add `#write` and `#close` to `Snappy::Writer`

### PR DESCRIPTION
**Pull request by okkez**
I want to use these methods in https://github.com/fluent/fluent-plugin-webhdfs

### CODE REVIEW

**Comment by miyucy** [comment]
thx :+1:

**Comment by okkez** [comment]
Wow :dash: 
Thank you for quick response!
Could you release new version?

**Comment by miyucy** [comment]
sure sure check it https://twitter.com/rubygems/status/695079619100303360

**Comment by okkez** [comment]
Thank you very much :heart:

**Pull request merged**
